name: cryptdart
version: 0.1.0
description: A Dart project under LGPL-3.0 license.
homepage: https://example.com
repository: https://example.com/cryptdart
license: LGPL-3.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  pointycastle: ^3.7.3
  basic_utils: ^5.6.0
dev_dependencies:
  test: ^1.24.0
